language: python

python:
  - '2.6'
  - '2.7'

before_install:
  - sudo apt-get update
  - sudo apt-get install --fix-broken --ignore-missing -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" swig supervisor rabbitmq-server ruby
  - sudo apt-get install --fix-broken --ignore-missing -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" python-m2crypto
  - pip install jinja2 --use-mirrors --mirrors=http://testpypi.python.org/pypi
  - pip install msgpack-python --use-mirrors --mirrors=http://testpypi.python.org/pypi
  - pip install pycrypto --use-mirrors --mirrors=http://testpypi.python.org/pypi
  - pip install PyYAML --use-mirrors --mirrors=http://testpypi.python.org/pypi
  - pip install "pyzmq>=2.1.9" --use-mirrors --mirrors=http://testpypi.python.org/pypi
  #- pip install http://dl.dropbox.com/u/174789/m2crypto-0.20.1.tar.gz
  - (git describe && git fetch --tags) || (git remote add upstream git://github.com/saltstack/salt.git && git fetch --tags upstream)
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors --mirrors=http://testpypi.python.org/pypi unittest2 ordereddict; fi"
  - pip install mock --use-mirrors --mirrors=http://testpypi.python.org/pypi
  - sudo find / -iname *M2Crypto* -print


install: pip install -r requirements.txt --use-mirrors --mirrors=http://testpypi.python.org/pypi

script: "sudo -E /home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/python setup.py test --runtests-opts='--run-destructive --sysinfo -v'"

notifications:
  irc:
    channels: "irc.freenode.org#salt-devel"
    on_success: change
    on_failure: change
