language: python

python:
  - '2.6'
  - '2.7'

before_install:
  - sudo add-apt-repository -y ppa:saltstack/salt
  - sudo apt-get update
  - sudo apt-get install --fix-broken --ignore-missing -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" libzmq3 python-zmq
  - sudo apt-get install --fix-broken --ignore-missing -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" swig supervisor rabbitmq-server ruby python-yaml python-m2crypto python-crypto msgpack-python python-jinja2
  - (git describe && git fetch --tags) || (git remote add upstream git://github.com/saltstack/salt.git && git fetch --tags upstream)
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors --mirrors=http://testpypi.python.org/pypi unittest2 ordereddict; fi"
  - pip install mock --use-mirrors --mirrors=http://testpypi.python.org/pypi

script: "sudo -E /home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/python setup.py test --runtests-opts='--run-destructive --sysinfo -v'"

install: echo "fake install line in order not to issue: install -r requirements.txt --use-mirrors"

notifications:
  irc:
    channels: "irc.freenode.org#salt-devel"
    on_success: change
    on_failure: change
