# -*- mode: ruby -*-
# vi: set ft=ruby fenc=utf-8 spell spl=en cc=120 sts=2 sw=2 et :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "saltstack-ubuntu-12.04.1-server-i386"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://github.com/downloads/s0undt3ch/vagrant-baseboxes/saltstack-ubuntu-12.04.1-server-i386.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  #config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  #config.vm.share_folder "salt-install", "/salt/source", "../../../"
  # Support symlinks
  #['v-root', 'v-data', 'salt-install'].each do |shared_folder|
  #  config.vm.customize [
  #    "setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/" + shared_folder, "1"
  #  ]
  #end

  # Use all the defaults:
  config.vm.provision :salt do |salt|
    #salt.run_highstate = true

    ## Optional Settings:
    salt.minion_config = "minion.conf"
    salt.salt_install_type = "git"
    salt.salt_install_args = "develop"

    ## your preseeded minion key
    salt.master = true
    #salt.minion_key = "/tmp/salttest/pki/master.pem"
    #salt.minion_pub = "/tmp/salttest/pki/master.pub"
  end

end
